# Generated by Django 2.2 on 2019-04-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, max_length=30, null=True, upload_to=''),
        ),
    ]
