# Generated by Django 2.2 on 2019-04-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0002_auto_20190427_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='nefosta.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
