# Generated by Django 2.2 on 2019-09-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0002_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTechnologyCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='colleges/')),
            ],
            options={
                'ordering': ('-posted_on',),
                'abstract': False,
            },
        ),
    ]
