# Generated by Django 2.2 on 2019-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0003_foodtechnologycollege'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='_url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
