# Generated by Django 2.2 on 2019-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0003_auto_20190427_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
