# Generated by Django 2.2 on 2019-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
