# Generated by Django 2.2 on 2019-04-28 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0005_auto_20190427_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-posted_on',)},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-posted_on', 'title')},
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ('-posted_on',)},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-posted_on',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-posted_on', 'title')},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-posted_on',)},
        ),
        migrations.AddField(
            model_name='album',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='career',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
