# Generated by Django 2.2 on 2019-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0010_downloadcategory_downloadresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album_name',
            new_name='album',
        ),
    ]
