# Generated by Django 2.2 on 2019-05-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefosta', '0011_auto_20190501_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='show_in_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
